language: go
go:
  - 1.11

go_import_path: github.com/nats-io/nats-rest-config-proxy
dist: xenial
sudo: false
install: true
script:
  - env GO111MODULE=on go test ./... -v
  - if [[ "$TRAVIS_GO_VERSION" =~ 1.11 ]]; then ./scripts/cov.sh TRAVIS; else GOGC=10 go test -race -p=1 $EXCLUDE_VENDOR; fi
